linux-arm64-task: 
  timeout_in: 90m
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder-arm64
    architecture: arm64
    platform: linux
    cpu: 4
    memory: 16G
  script:
    - cd linux
    - ARCHITECTURES="arm64" rake image
    - ARCHITECTURES="arm64" rake
    - ls
linux-x86_64_task: 
  timeout_in: 90m
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 4
    memory: 16G
  script:
    - cd linux
    - ARCHITECTURES="x86_64" rake image
    - ARCHITECTURES="x86_64" rake
    - ls
macosx-arm64-task: 
  timeout_in: 90m
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  script:
    - find osx/ -type f -exec chmod +x {} \;
    - chmod +x shared/package
    - mkdir -p "build"
    - rbenv local system
    - sudo gem install bundler:2.3.17
    - rbenv global 3.2.2
    - cd osx
    - rake stash_conflicting_paths
    - rake --trace
    - cp -R traveling-ruby* ../build
  binary_artifacts:
    path: "build/*"
macosx-x86_64_task: 
  timeout_in: 90m
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  script:
    - rbenv local system
    - sudo gem install bundler:2.3.17
    - rbenv global 3.2.2
    - softwareupdate --install-rosetta --agree-to-license
    - cd osx
    - rake stash_conflicting_paths
    - arch -x86_64 rake --trace
    - rake unstash_conflicting_paths
    - ls
windows_task: 
  timeout_in: 90m
  windows_container:
    image: cirrusci/windowsservercore:2019
  script: |
      uname -m
      cd windows
      sh -c 'mkdir -p cache output/3.2.2'
      sh -c './build-ruby -a x86 -r 3.2.2 cache output/3.2.2'
      sh -c './package -r traveling-ruby-20230428-3.2.2-x86-windows.tar.gz output/3.2.2'
      sh -c 'ls'
      sh -c 'rm -rf cache output/3.2.2'
      sh -c 'mkdir -p cache output/3.2.2'
      sh -c './build-ruby -a x86_64 -r 3.2.2 cache output/3.2.2'
      sh -c './package -r traveling-ruby-20230428-3.2.2-x86_64-windows.tar.gz output/3.2.2'
      sh -c 'ls'


# skip: "changesInclude('.github/**','.circleci/**')"

