macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-base:latest

task:
  script:
    - echo "Hello World from macOS!"
    - uname -m
    - ruby --version
    - rbenv install --list
    - rbenv versions
    - rbenv local system
    - sudo gem install bundler:2.3.17
    - rbenv local 3.0.5
    - softwareupdate --install-rosetta --agree-to-license
    - rm .ruby-version
    - cd osx
    - rake stash_conflicting_paths
    - rake --trace
    - rake unstash_conflicting_paths
    - ls
