name: Linux
on:
  push:
    branches: [ main, ci ]
#   pull_request:
#     branches: [ main ]

jobs:
  make-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
            version: 3.1.2
      - name: 
        run: |
            cd linux
            rake
            ls
      - name: 'Upload Artifact - linux arm64'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-20230504-3.1.2-linux-arm64.tar.gz
          path: traveling-ruby-20230504-3.1.2-linux-arm64.tar.gz
      - name: 'Upload Artifact - linux x86_64'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-20230504-3.1.2-linux-x86_64.tar.gz
          path: traveling-ruby-20230504-3.1.2-linux-x86_64.tar.gz
  make-windows:
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
            version: 3.1.2
      - name: 
        run: |
            cd windows
            sh -c 'mkdir -p cache output/3.1.2'
            sh -c './build-ruby -a x86_64 -r 3.1.2 cache output/3.1.2'
            sh -c './package -r traveling-ruby-20230504-3.1.2-x86_64-win32.tar.gz output/3.1.2'
            sh -c 'ls'
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-20230504-3.1.2-x86_64-win32.tar.gz
          path: traveling-ruby-20230504-3.1.2-x86_64-win32.tar.gz
  make-osx:
    strategy:
      matrix:
        os: [macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
            version: 3.1.2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: '14.2'
      - name: 
        run: |
            cd osx
            rake stash_conflicting_paths
            rake
            rake unstash_conflicting_paths
            ls
      - name: 'Upload Artifact- osx arm64'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-20230504-3.1.2-osx-arm64.tar.gz
          path: traveling-ruby-20230504-3.1.2-osx-arm64.tar.gz
      - name: 'Upload Artifact- osx x86_64'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-20230504-3.1.2-osx-x86_64.tar.gz
          path: traveling-ruby-20230504-3.1.2-osx-x86_64.tar.gz