name: Linux
on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]

jobs:
  make:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
            version: 3.1.2
      - name: 
        run: |
            cd linux
            rake image
            rake