name: MacOS arm64
on:
  push:
    branches: [ main, ci ]
#   pull_request:
#     branches: [ main ]

jobs:
  make-osx-arm64:
    strategy:
      matrix:
        os: [self-hosted]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: |
            brew install rbenv
            rbenv local system
            sudo gem install bundler:2.3.17
            rbenv install 3.1.2
            rbenv global 3.1.2
      - name: build arm64
        run: |
            cd osx
            rake stash_conflicting_paths
            rake --trace
            rake unstash_conflicting_paths
            ls
        env:
          DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
      - name: 'Upload Artifact- osx arm64'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-20230504-3.1.2-osx-arm64.tar.gz
          path: osx/traveling-ruby-20230504-3.1.2-osx-arm64.tar.gz