name: Linux
on:
  push:
    branches: [ main, ci ]
#   pull_request:
#     branches: [ main ]

jobs:
  # make-ubuntu:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]
  #     fail-fast: false
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: "Set up Ruby"
  #       uses: ruby/setup-ruby@v1
  #       with:
  #           ruby-version: 3.1.2
  #     - name: package
  #     # needed if cross compiling for arm64
  #             # docker run --privileged --rm tonistiigi/binfmt --install all
  #       run: |
  #           cd linux
  #           rake
  #           ls
  #       env:
  #         ARCHITECTURES: "x86_64"
  #     # - name: 'Upload Artifact - linux arm64'
  #     #   uses: actions/upload-artifact@v3
  #     #   with:
  #     #     name: traveling-ruby-20230504-3.1.2-linux-arm64.tar.gz
  #     #     path: linux/traveling-ruby-20230504-3.1.2-linux-arm64.tar.gz
  #     - name: 'Upload Artifact - linux x86_64'
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: traveling-ruby-20230504-3.1.2-linux-x86_64.tar.gz
  #         path: linux/traveling-ruby-20230504-3.1.2-linux-x86_64.tar.gz
  make-ubuntu-arm64:
    strategy:
      matrix:
        os: [self-hosted]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: setup self-hosted deps
        run: |
          # sudo apt install snapd
          # sudo snap install docker
          # sudo addgroup --system docker
          # sudo adduser $USER docker
          # newgrp docker
          sudo snap disable docker
          sudo snap enable docker
          # sudo apt install -y git curl libssl-dev libreadline-dev zlib1g-dev autoconf bison build-essential libyaml-dev libreadline-dev libncurses5-dev libffi-dev libgdbm-dev
          # curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
          # eval "$(/home/ubuntu/.rbenv/bin/rbenv init - bash)"
          # rbenv install 3.1.2
          # rbenv global 3.1.2
      - name: package
        run: |
            eval "$(/home/ubuntu/.rbenv/bin/rbenv init - bash)"
            cd linux
            rake
            ls
        env:
          ARCHITECTURES: "arm64"
      - name: 'Upload Artifact - linux arm64'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-20230504-3.1.2-linux-arm64.tar.gz
          path: linux/traveling-ruby-20230504-3.1.2-linux-arm64.tar.gz